[versions]

kotlin = "1.8.10"
exposed = "0.41.1"
wdater = "0.0.2"

[libraries]

# exposed
exposedCore = { module = "org.jetbrains.exposed:exposed-core", version.ref = "exposed" }

# gradle plugins
kotlinPlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
